image: opensuse/tumbleweed:latest

install_guix:
    stage: build
        - zypper install -y guix
        - guix-daemon --build-users-group=guixbuild &
        - guix pull
    artifacts:
        paths:
            - /var/guix/*
            - /gnu/store/*

macbook41:
    script:
        - guix system build macbook41_config.scm

E2140:
    script:
        - guix system build E2140_config.scm
