image: opensuse/tumbleweed:latest

build:installGuix:
    stage: build
        - zypper install -y guix
        - guix-daemon --build-users-group=guixbuild &
        - guix pull

macbook41:
    script:
        - guix system build macbook41_config.scm
    dependencies:
        build:installGuix

E2140:
    script:
        - guix system build E2140_config.scm
    dependencies:
        build:installGuix
