image: opensuse/tumbleweed:latest

installGuix:
    stage: build
    script:
        - zypper addrepo --no-gpgcheck https://download.opensuse.org/repositories/home:/jbrielmaier:/guix/openSUSE_Tumbleweed/home:jbrielmaier:guix.repo
        - zypper install -y guix
        - guix-daemon --build-users-group=guixbuild &
        - guix pull

macbook41:
    script:
        - guix system build macbook41_config.scm
    dependencies:
        - installGuix

E2140:
    script:
        - guix system build E2140_config.scm
    dependencies:
        - installGuix
