image: opensuse/tumbleweed:latest

cache:
    paths:
        - /var/guix/*
        - /gnu/store/*

before_script:
    - zypper install -y guix
    - guix-daemon --build-users-group=guixbuild &
    - guix pull

macbook41:
    script:
        - guix system build macbook41_config.scm

E2140:
    script:
        - guix system build E2140_config.scm
