image: opensuse/tumbleweed:latest

installGuix:
    stage: build
    script:
        - zypper addrepo --no-gpgcheck https://download.opensuse.org/repositories/home:/jbrielmaier:/guix/openSUSE_Tumbleweed/home:jbrielmaier:guix.repo
        - zypper install -y guix
        - guix-daemon --build-users-group=guixbuild &
    artifacts:
        paths:
            - /var/guix/*
            - /gnu/store/*

macbook41:
    script:
        - pwd
        - echo $PATH
        - whoami
        - ls /var/guix/profiles/per-user/*/*
        - guix system build macbook41_config.scm
    dependencies:
        - installGuix

E2140:
    script:
        - guix system build E2140_config.scm
    dependencies:
        - installGuix
